Show all items in feed and selectively delete items
thefranke/rss-librarian pull request #3
Opened 2024-12-28 16:34 UTC by aberamseyer

<img width="808" alt="image" src="https://github.com/user-attachments/assets/65c80b9f-f756-4cb3-a3bc-d8607f102ba9" />

Adds two features:
1. A list of all the items in the current feed
2. A button to selectively delete each item

2025-01-04 15:25 UTC, thefranke commented
Hey Abe, great addition. Tested it a bit and most of it is working as expected. Please address two small issues before I merge.

2025-01-04 15:35 UTC, thefranke requested changes
Again great feature, please make the small adjustments and I'll merge it! Thank you

2025-01-04 15:35 UTC, thefranke commented on librarian.php
> +            header('Location: /?id='.$param_id);
Please change to `header('Location: ' .$g_url_librarian. '/?id='.$param_id);`

2025-01-04 15:35 UTC, thefranke commented on librarian.php
> +            header('Location: /?id='.$param_id);
This way the correct librarian.php file is called, instead of assuming the URL is at the root.

2025-01-04 15:35 UTC, thefranke commented on librarian.php
> +            header('Location: /?id='.$param_id);
`header('Location: ' .$g_url_librarian. '/?id='.$param_id);`

See above.

2025-01-04 15:35 UTC, thefranke commented on librarian.php
> +                print_r('<li><a href="?id='.$user_id.'&delete=1&url='.urlencode($item->guid).'" onclick="return confirm(\'Delete?\')">❌</a> <a href="'.$item->guid.'" target="_blank">'.$item->title.'<
Please use HTML encoding for the emoji: `&#10060;` instead of ❌ so that the HTML validates. You can check it yourself here with the [W3 Validator.](https://validator.w3.org/)

2025-01-27 20:32 UTC, merged

2025-01-27 20:32 UTC, thefranke commented
Actually never mind, I will add the changes after the merge

2025-11-09 17:41 UTC, aberamseyer commented
hey just wanted to say sorry I totally forgot about this PR and didn’t see your comments. I only came back to this after seeing your blog post today. Congrats on the 1.0 release!

2025-11-15 22:27 UTC, thefranke commented
No problem, the issues were minor anyhow. I think I'll leave the code be for a month or so and then start thinking about follow-up features for the next major release.